# Generated by Django 5.0.6 on 2024-05-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveSmallIntegerField(default=8)),
                ('weight', models.PositiveSmallIntegerField(default=180)),
                ('bacon', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('sosat', models.IntegerField()),
            ],
        ),
    ]
