# Generated by Django 5.0.6 on 2024-05-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_burgermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burgermodel',
            old_name='date',
            new_name='make_date',
        ),
        migrations.RenameField(
            model_name='burgermodel',
            old_name='sosat',
            new_name='pok',
        ),
        migrations.AddField(
            model_name='burgermodel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
