# Generated by Django 5.0.6 on 2024-05-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_rename_date_burgermodel_make_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burgermodel',
            name='pok',
        ),
    ]
