# Generated by Django 5.0.6 on 2024-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_remove_burgermodel_pok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burgermodel',
            name='available',
        ),
        migrations.RemoveField(
            model_name='burgermodel',
            name='bacon',
        ),
        migrations.RemoveField(
            model_name='burgermodel',
            name='make_date',
        ),
        migrations.RemoveField(
            model_name='burgermodel',
            name='weight',
        ),
        migrations.AlterField(
            model_name='burgermodel',
            name='price',
            field=models.IntegerField(default=8),
        ),
    ]
